bin2dec: Better err handling init replace

diff --git a/bin2dec b/bin2dec
--- a/bin2dec
+++ b/bin2dec
@@ -5,7 +5,7 @@
 ## Login   <ronan.boiteau@epitech.net>
 ## 
 ## Started on  Mon Jan  2 01:06:45 2017 Ronan Boiteau
-## Last update Mon Jan  2 15:29:45 2017 Ronan Boiteau
+## Last update Mon Jan  2 16:15:15 2017 Ronan Boiteau
 ##
 
 check_usage()
@@ -18,17 +18,11 @@ check_usage()
 	exit 1
     fi
 
-    binary="$1"
-    char_pos=$(echo "$binary" | wc -m)
-    (( char_pos-- ))
-    while (( char_pos > 0 )) ; do
-	(( char_pos-- ))
-	# expr substr hello 2 1
-	if [ "${binary:$char_pos:1}" != "0" ] && [ "${binary:$char_pos:1}" != "1" ] ; then
-	    >&2 echo "Error"
-	    exit 1
-	fi
-    done
+    echo "$1" | grep -qE "^[01]+$"
+    if (( $? == 1 )) ; then
+	>&2 echo "Error"
+	exit 1
+    fi
 }
 
 bin2dec()
