fix factorial error

diff --git a/factorial b/factorial
--- a/factorial
+++ b/factorial
@@ -5,7 +5,7 @@
 ## Login   <ronan.boiteau@epitech.net>
 ## 
 ## Started on  Mon Jan  2 17:36:13 2017 Ronan Boiteau
-## Last update Tue Jan  3 13:55:13 2017 Ronan Boiteau
+## Last update Tue Jan  3 15:40:19 2017 Ronan Boiteau
 ##
 
 check_usage()
@@ -20,7 +20,7 @@ check_usage()
 
     echo "$1" | grep -qE "^[0-9]+$"
     if [ "$?" -ne 0 ] ; then
-	>&2 echo "ERROR"
+	>&2 echo "Error"
 	exit 1
     fi
 }
@@ -29,7 +29,7 @@ find_factorial()
 {
     nbr=$1
     if [ "$nbr" -gt 20 ] ; then
-	>&2 echo "ERROR"
+	>&2 echo "Error"
 	exit 1
     fi
     result=1
