killall

diff --git a/killall b/killall
--- a/killall
+++ b/killall
@@ -5,7 +5,7 @@
 ## Login   <ronan.boiteau@epitech.net>
 ## 
 ## Started on  Tue Jan  3 15:43:57 2017 Ronan Boiteau
-## Last update Tue Jan  3 18:21:42 2017 Ronan Boiteau
+## Last update Tue Jan  3 18:45:03 2017 Ronan Boiteau
 ##
 
 print_usage()
@@ -85,17 +85,20 @@ kill_pid()
     done
 }
 
-# kill_prog()
-# {
-#     while [ "$#" -gt 1 ] ; do
-# 	kill "$2" 2>/dev/null
-# 	if [ $? -eq 1 ] ; then
-# 	    echo "ERROR: pid $2 : no process found"
-# 	    exit_status=1
-# 	fi
-# 	shift
-#     done
-# }
+kill_prog()
+{
+    while [ "$#" -gt 1 ] ; do
+	user_pids=$(ps -ef | sed '1d' | sed 's/ \+/ /g' | grep "$2" | cut -d' ' -f2)
+	echo $user_pids | tr ' ' '\n' | while read line ; do
+	    kill "$line" 2>/dev/null
+	    if [ $? -eq 1 ] ; then
+		echo "ERROR: pid $2 : no process found"
+		exit_status=1
+	    fi
+	done
+	shift
+    done
+}
 
 kill_all()
 {
