killall

diff --git a/killall b/killall
--- a/killall
+++ b/killall
@@ -5,7 +5,7 @@
 ## Login   <ronan.boiteau@epitech.net>
 ## 
 ## Started on  Tue Jan  3 15:43:57 2017 Ronan Boiteau
-## Last update Tue Jan  3 17:59:01 2017 Ronan Boiteau
+## Last update Tue Jan  3 18:21:42 2017 Ronan Boiteau
 ##
 
 print_usage()
@@ -58,17 +58,6 @@ option_parser()
     fi
 }
 
-kill_pid()
-{
-    while [ "$#" -gt 1 ] ; do
-	kill "$2" 2>/dev/null
-	if [ $? -eq 1 ] ; then
-	    echo "ERROR: pid $2 : no process found"
-	fi
-	shift
-    done
-}
-
 kill_user()
 {
     while [ "$#" -gt 1 ] ; do
@@ -77,6 +66,46 @@ kill_user()
 	    kill "$line" 2>/dev/null
 	    if [ $? -eq 1 ] ; then
 		echo "ERROR: pid $2 : no process found"
+		exit_status=1
+	    fi
+	done
+	shift
+    done
+}
+
+kill_pid()
+{
+    while [ "$#" -gt 1 ] ; do
+	kill "$2" 2>/dev/null
+	if [ $? -eq 1 ] ; then
+	    echo "ERROR: pid $2 : no process found"
+	    exit_status=1
+	fi
+	shift
+    done
+}
+
+# kill_prog()
+# {
+#     while [ "$#" -gt 1 ] ; do
+# 	kill "$2" 2>/dev/null
+# 	if [ $? -eq 1 ] ; then
+# 	    echo "ERROR: pid $2 : no process found"
+# 	    exit_status=1
+# 	fi
+# 	shift
+#     done
+# }
+
+kill_all()
+{
+    while [ "$#" -gt 1 ] ; do
+	user_pids=$(ps -ef | sed '1d' | sed 's/ \+/ /g' | cut -d' ' -f2)
+	echo $user_pids | tr ' ' '\n' | while read line ; do
+	    kill "$line" 2>/dev/null
+	    if [ $? -eq 1 ] ; then
+		echo "ERROR: pid $2 : no process found"
+		exit_status=1
 	    fi
 	done
 	shift
@@ -86,6 +115,7 @@ kill_user()
 main()
 {
     readonly progname="$0"
+    exit_status=0
 
     option_parser "$@"
     if [ $mode == "user" ] ; then
@@ -97,7 +127,7 @@ main()
     elif [ $mode == "all" ] ; then
 	kill_all "$@"
     fi
-    exit 0
+    exit $exit_status
 }
 
 main "$@"
