Fix safe_erase

diff --git a/safe_erase b/safe_erase
--- a/safe_erase
+++ b/safe_erase
@@ -1,40 +1,40 @@
 #!/bin/bash
 
-_check_usage()
+check_usage()
 {
-    readonly ARGC="$1"
+    readonly argc="$1"
     
-    if (( "$ARGC" != 1 )) ; then
- 	echo "Usage: $PROGNAME [FILE|FOLDER]"
-	exit 1
+    if (( "$argc" != 1 )) ; then
+        echo "Usage: $progname [FILE|FOLDER]"
+        exit 1
     fi
     return 0
 }
 
-_check_filepath()
+check_filepath()
 {
-    if [[ ! -f "$FILEPATH" ]] ; then
-	echo "$PROGNAME: cannot encrypt ‘$FILEPATH’: No such file"
-	if [[ -d "$1" ]] ; then
-	    echo "$PROGNAME does not support directories at this time"
-	fi
-	exit 1
+    if [[ ! -f "$filepath" ]] ; then
+        echo "$progname: cannot encrypt ‘$filepath’: No such file"
+        if [[ -d "$1" ]] ; then
+            echo "$progname does not support directories at this time"
+        fi
+        exit 1
     fi
     return 0
 }
 
 main()
 {
-    _check_usage "$#"
-    readonly FILEPATH="$1"
-    _check_filepath "$FILEPATH"
+    check_usage "$#"
+    readonly filepath="$1"
+    check_filepath
 
     echo -e "How many passes? \c"
-    read PASSES
-    shred -vfuz --iterations=$PASSES "$1"
+    read passes
+    shred -vfuz --iterations=$passes "$1"
 
     exit 0
 }
 
-readonly PROGNAME="safe_erase"
+readonly progname="safe_erase"
 main "$@"
