Fix upcase_lowcase

diff --git a/upcase_lowcase b/upcase_lowcase
--- a/upcase_lowcase
+++ b/upcase_lowcase
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 print_usage()
 {
@@ -10,40 +10,40 @@ print_usage()
 
 option_parser()
 {
-    mode="none"
+    let mode="none"
     
     while [ "$#" -gt 0 ] ; do
-	arg="$1"
-	case $arg in
-	    -l)
-		mode="lowcase"
-		;;
-	    -u)
-		mode="upcase"
-		;;
-	    -*)
-		>&2 echo "ERROR: $arg unknown option"
-		exit 1
-		;;
-	    *)
-		print_usage
-		;;
-	esac
-	shift
+        arg="$1"
+        case "$arg" in
+            -l)
+                mode="lowcase"
+            ;;
+            -u)
+                mode="upcase"
+            ;;
+            -*)
+                >&2 echo "ERROR: $arg unknown option"
+                exit 1
+            ;;
+            *)
+                print_usage
+            ;;
+        esac
+        shift
     done
     if [ "$mode" = "none" ] ; then
-	print_usage
+        print_usage
     fi
 }
 
 upcase_lowcase()
 {
     while read line ; do
-	if [ "$mode" = "lowcase" ] ; then
-	    echo "$line" | tr '[:upper:]' '[:lower:]'
-	else
-	    echo "$line" | tr '[:lower:]' '[:upper:]'
-	fi
+        if [ "$mode" = "lowcase" ] ; then
+            echo "$line" | tr '[:upper:]' '[:lower:]'
+        else
+            echo "$line" | tr '[:lower:]' '[:upper:]'
+        fi
     done
 }
 
